name: Build RPM

on: [push, pull_request]

jobs:
  build-rpm:
    name: Build RPM package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Build package
      id: build
      uses: polistern/build-rpm-centos7@master
      with:
        spec: "contrib/rpm/pboted-git.spec"
        install: cmake make
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.build.outputs.filename }}
        path: ${{ steps.build.outputs.filename }}
