name: Build

on: [push, pull_request]

jobs:
  build:
    name: CMake build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout  
      uses: actions/checkout@v3
    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install \
          build-essential \
          cmake \
          libboost-system-dev \
          libboost-program-options-dev \
          libmimetic-dev \
          libssl-dev \
          zlib1g-dev
    - name: Build application
      run: |
        cd build
        cmake .
        make -j3
